import { FlatCompat } from "@eslint/eslintrc";

// Next 16 removed `next lint`; ESLint 9 uses flat config. This bridges the existing
// eslint-config-next rules (core-web-vitals + typescript) into flat config.
const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // next-env.d.ts is generated by Next and uses a triple-slash reference by design.
  { ignores: [".next/**", "out/**", "node_modules/**", "scripts/**", "next-env.d.ts"] },
];

export default config;
