import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const frontendDir = path.resolve(__dirname, "..");
const standaloneRootDir = path.join(frontendDir, ".next", "standalone");
const staticDir = path.join(frontendDir, ".next", "static");
const publicDir = path.join(frontendDir, "public");
const deployDir = path.join(frontendDir, ".deploy", "synergy");

async function pathExists(targetPath) {
  try {
    await fs.access(targetPath);
    return true;
  } catch {
    return false;
  }
}

async function rmDirQuiet(targetPath) {
  if (!(await pathExists(targetPath))) {
    return;
  }
  await fs.rm(targetPath, { recursive: true, force: true });
}

/** Build into a fresh staging dir, then merge into `synergy` without deleting `synergy` first (avoids Windows EBUSY when a Node process is still serving that folder). */
async function prepareStagingDir() {
  const base = path.join(frontendDir, ".deploy", "_synergy_staging");
  try {
    await rmDirQuiet(base);
    await fs.mkdir(base, { recursive: true });
    return base;
  } catch {
    const fallback = path.join(
      frontendDir,
      ".deploy",
      `_synergy_staging_${Date.now()}`,
    );
    await rmDirQuiet(fallback);
    await fs.mkdir(fallback, { recursive: true });
    return fallback;
  }
}

if (!(await pathExists(standaloneRootDir))) {
  throw new Error(
    "Standalone build output was not found. Run `next build` with `output: \"standalone\"` enabled first.",
  );
}

const stagingDir = await prepareStagingDir();

await fs.cp(standaloneRootDir, stagingDir, { recursive: true, force: true });

if (await pathExists(staticDir)) {
  await fs.cp(staticDir, path.join(stagingDir, "frontend", ".next", "static"), {
    recursive: true,
    force: true,
  });
}

if (await pathExists(publicDir)) {
  await fs.cp(publicDir, path.join(stagingDir, "frontend", "public"), {
    recursive: true,
    force: true,
  });
}

// cPanel Node.js app (e.g. Synergy) expects `app.js` in the application root.
// Next standalone emits the real server at `frontend/server.js`; this file only delegates.
const appJsPath = path.join(stagingDir, "app.js");
const appJsSource = `"use strict";
// Generated by scripts/package-synergy.mjs. Edit the script, not this file in deploy.
require("./frontend/server.js");
`;
await fs.writeFile(appJsPath, appJsSource, "utf8");

// Replace Next-copied monorepo package.json (with workspaces) so cPanel "Run NPM Install"
// cannot clobber traced node_modules/next. Stub has no dependencies/workspaces.
const stubPackageJson = {
  name: "next-project-baseplate-synergy",
  version: "1.0.0",
  private: true,
  main: "app.js",
  engines: { node: ">=20.0.0 <21.0.0" },
  scripts: { start: "node app.js" },
};
await fs.writeFile(
  path.join(stagingDir, "package.json"),
  `${JSON.stringify(stubPackageJson, null, 2)}\n`,
  "utf8",
);

const nextServerJs = path.join(
  stagingDir,
  "node_modules",
  "next",
  "dist",
  "server",
  "next.js",
);
if (!(await pathExists(nextServerJs))) {
  throw new Error(
    `Deploy package is missing Next runtime at ${nextServerJs}. ` +
      `The standalone trace is incomplete; run a clean \`next build\` and retry.`,
  );
}

await fs.mkdir(path.dirname(deployDir), { recursive: true });
try {
  await rmDirQuiet(deployDir);
} catch (err) {
  if (err && (err.code === "EBUSY" || err.code === "EPERM")) {
    console.warn(
      `Could not remove ${deployDir} (${err.code}); merging over existing files (close any process using that folder for a clean deploy next time).`,
    );
  } else {
    throw err;
  }
}
await fs.cp(stagingDir, deployDir, { recursive: true, force: true });

try {
  await rmDirQuiet(stagingDir);
} catch {
  console.warn(
    `Could not remove staging folder ${stagingDir}; delete it manually if it remains.`,
  );
}

console.log(`cPanel/Synergy deploy package created at ${deployDir}`);
